package constants

const (
	PARSING_ERROR        = "PARSING_ERROR"
	REGISTER_BODY_PARSED = "REGISTER_BODY_PARSED"
	VALIDATION_ERROR     = "VALIDATION_ERROR"
	ALREADY_EXISTS       = "ALREADY_EXISTS"
	BUSINESS_REGISTERED  = "BUSINESS_REGISTERED"
	MAIL_ERROR  = "MAIL_ERROR"
	NOT_FOUND  = "NOT_FOUND"
)
